### ISSUE TITLE
Error when upgrading from 2.2.3 to 2.3.0

### ISSUE THREAD

**Issue by benaldred** [clickfunnels2/refine-rails#64]
Putting this here just in case there is an easy fix or it's been seen before...

When I upgrade to the latest `@hammerstone/refine-stimulus` I get this error when webpack is compiling. 

It looks like my postCSS is trying to load the daterangepicker.css 

```
ERROR in ./node_modules/daterangepicker/daterangepicker.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/dist/cjs.js??ref--6-2!./node_modules/daterangepicker/daterangepicker.css)
10:16:11 web.1     | Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
10:16:11 web.1     | TypeError: this.getOptions is not a function
10:16:11 web.1     |     at Object.loader (/Users/ben/workspace/consent-kit/consentkit.io/node_modules/postcss-loader/dist/index.js:40:24)
10:16:11 web.1     |  @ ./node_modules/daterangepicker/daterangepicker.css 2:12-134 9:17-24 13:15-22
10:16:11 web.1     |  @ ./node_modules/@hammerstone/refine-stimulus/app/assets/javascripts/refine-stimulus.esm.js
10:16:11 web.1     |  @ ./app/frontend/controllers/index.js
10:16:11 web.1     |  @ ./app/frontend/packs/document.js
```

I cannot work out how to ignore `node_modules/daterangepicker/daterangepicker.css` 

Ideally, this would be an external dependency as I don't need it.
